# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\uis\PatientForm.ui'
#
# Created: Fri Nov 21 19:51:47 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pacientForm(object):
    def setupUi(self, pacientForm):
        pacientForm.setObjectName("pacientForm")
        pacientForm.resize(543, 444)
        self.verticalLayout = QtWidgets.QVBoxLayout(pacientForm)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(pacientForm)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.ciLabel = QtWidgets.QLabel(self.widget)
        self.ciLabel.setObjectName("ciLabel")
        self.gridLayout.addWidget(self.ciLabel, 0, 0, 1, 1)
        self.ciInput = QtWidgets.QLineEdit(self.widget)
        self.ciInput.setObjectName("ciInput")
        self.gridLayout.addWidget(self.ciInput, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.nameInput = QtWidgets.QLineEdit(self.widget)
        self.nameInput.setObjectName("nameInput")
        self.gridLayout.addWidget(self.nameInput, 1, 2, 1, 1)
        self.ageInput = QtWidgets.QSpinBox(self.widget)
        self.ageInput.setMaximum(200)
        self.ageInput.setSingleStep(5)
        self.ageInput.setProperty("value", 30)
        self.ageInput.setObjectName("ageInput")
        self.gridLayout.addWidget(self.ageInput, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.provinceCombo = QtWidgets.QComboBox(self.widget)
        self.provinceCombo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.provinceCombo.setObjectName("provinceCombo")
        self.gridLayout.addWidget(self.provinceCombo, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(pacientForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.buttonsWidget = QtWidgets.QWidget(pacientForm)
        self.buttonsWidget.setObjectName("buttonsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonsWidget)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.appBtn = QtWidgets.QPushButton(self.buttonsWidget)
        self.appBtn.setObjectName("appBtn")
        self.horizontalLayout.addWidget(self.appBtn)
        self.acBtn = QtWidgets.QPushButton(self.buttonsWidget)
        self.acBtn.setObjectName("acBtn")
        self.horizontalLayout.addWidget(self.acBtn)
        self.tacBtn = QtWidgets.QPushButton(self.buttonsWidget)
        self.tacBtn.setObjectName("tacBtn")
        self.horizontalLayout.addWidget(self.tacBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.saveBtn = QtWidgets.QPushButton(self.buttonsWidget)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.buttonsWidget)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.verticalLayout.addWidget(self.buttonsWidget)

        self.retranslateUi(pacientForm)
        self.cancelBtn.clicked.connect(pacientForm.close)
        QtCore.QMetaObject.connectSlotsByName(pacientForm)

    def retranslateUi(self, pacientForm):
        _translate = QtCore.QCoreApplication.translate
        pacientForm.setWindowTitle(_translate("pacientForm", "Form"))
        self.ciLabel.setText(_translate("pacientForm", "CI"))
        self.ciInput.setInputMask(_translate("pacientForm", "99999999999"))
        self.label.setText(_translate("pacientForm", "Nombre"))
        self.label_2.setText(_translate("pacientForm", "Provincia"))
        self.label_3.setText(_translate("pacientForm", "Edad"))
        self.appBtn.setToolTip(_translate("pacientForm", "Antecedentes Patológicos Personales"))
        self.appBtn.setText(_translate("pacientForm", "APP"))
        self.acBtn.setToolTip(_translate("pacientForm", "Análisis Complementarios"))
        self.acBtn.setText(_translate("pacientForm", "AC"))
        self.tacBtn.setText(_translate("pacientForm", "TAC"))
        self.saveBtn.setText(_translate("pacientForm", "Guardar"))
        self.cancelBtn.setText(_translate("pacientForm", "Cancelar"))

